version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./business-ngo-connect
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  recommendation-system:
    build:
      context: ./recommendation-system
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: